# Generated by Django 5.0.14 on 2026-04-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_unique_constraints_from_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='document_type_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='officedepartment',
            name='office_department_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userroleconfig',
            name='user_role_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
