# Generated by Django 5.0.14 on 2026-04-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_documenttype_document_type_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingdocument',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='received_by',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
